# zsh is a shell designed for interactive use, although it is also a powerful scripting language.
zsh:
	bash scripts\install-zsh.sh

# nvm is a version manager for node.js, designed to be installed per-user, and invoked per-shell.
nvm:
	bash scripts\install-nvm.sh
